var keystone = require('keystone'),
	Types = keystone.Field.Types;
var uuid = require('node-uuid');

/**
 * Innlog Model
 * ==========
 */

var Statistical = new keystone.List('Statistical', {
	map: { name: 'logDate' }});

Statistical.add({
	logDate:{type:Number,default:((Date.now())/1000),required:true,index:true},
	firstDate:{type:Number,default:((Date.now())/1000),required:true,index:true},
	lastDate:{type:Number,default:((Date.now())/1000),required:true,index:true},
	tType:{type:Types.Select,options:[
		{value:0,label:"实时统计"},//默认为实时统计
		{value:1,labal:"日阶段统计"},
		{value:2,label:"周阶段统计"},
		{value:3,label:"月阶段统计"}
		],index:true},
	sType: { type: Types.Select, index:true,options: [
//######begin
//pattern: (\d+)	( .+)
//replace:		{value:'$2',label:"$3"},
	{value:'1',label:"在线人数"},
	{value:'2',label:"新用户数量(无用)"},
	{value:'3',label:"用户数量"},
	{value:'4',label:"Session数量"},
	{value:'5',label:"新增添用户数量"},
	{value:'6',label:"ActiveUser"},
	{value:'7',labal:"消费宝石数"},
	{value:'8',label:"购买宝石数"},
	{value:'9',label:"MessageError"},
	{value:'10',label:"HandlerError"},
	{value:'11',label:"付费玩家数"},
	{value:'101',label:"总注册用户"},
	// {value:'1001',label:"周总注册用户"},
	// {value:'10001',label:"月总注册用户"},
	{value:'102',label:"新增注册用户"},
	// {value:'1002',label:"周新增注册用户"},
	// {value:'10002',label:"月新增注册用户"},
	{value:'103',label:"用户登录次数去重"},
	// {value:'1003',label:"周用户登录次数"},
	// {value:'10003',label:"月用户登录次数"},
	{value:'104',label:"用户登录次数"},
	// {value:'1004',label:"周总用户登录次数"},
	// {value:'10004',label:"月总用户登录次数"},
	{value:'105',label:"用户平均登录次数"},
	// {value:'1005',label:"周用户平均登录次数"},
	// {value:'10005',label:"月用户平均登陆次数"},
	{value:'106',label:"活跃用户"},
	// {value:'1006',label:"周活跃用户"},
	// {value:'10006',label:"月活跃用户"},
	{value:'107',label:"峰值在线"},
	// {value:'1007',label:"周峰值在线"},
	// {value:'10007',label:"月峰值在线"},
	{value:'108',label:"平均在线"},
	// {value:'1008',label:"周平均在线"},
	// {value:'10008',label:"月平均在线"},
	{value:'109',label:"流失用户"},
	// {value:'1009',label:"周流失用户"},
	// {value:'10009',label:"月流失用户"},
	{value:'110',label:"留存"},
	{value:"111",label:"充值宝石数"},//buygembuy
	{value:"112",label:"付费用户数"},
	{value:"113",label:"付费用户所占比例"},
	{value:"114",label:"付费用户与活跃用户比例"},
	{value:"115",label:"总付费次数"},
	{value:"116",label:"每个用户平均付费次数"},
	{value:"117",label:"阶段收入"},
	{value:"118",label:"ARPU"},
	{value:"119",label:"ARPPU"},
	{value:"120",label:"转化率"},
	{value:"121",label:"总转化率"},
	{value:"122",label:"新增用户转化率"},
	{value:"123",label:"总付费用户数"},
	{value:"124",label:"酒馆等级分布"},
	{value:"125",label:"冒险者数量分布"},
	{value:"126",label:"传奇/普通冒险者分布"},
	{value:"127",label:"冒险者星级分布"},
	{value:"128",label:"进阶等级分布"},
	{value:"129",label:"关卡完成情况分布"},
	{value:"130",label:"Task分布"},
	{value:"131",label:"Tutorial完成分布"},
	{value:"132",label:"付费内容分布"},
	{value:"133",label:"每次游戏时间分布"},
	{value:"134",label:"每天游戏时间分布"},
	{value:"135",label:"错误类型分布"},
	{value:"136",label:"一星冒险者等级分布"},
	{value:"137",label:"二星冒险者等级分布"},
	{value:"138",label:"三星冒险者等级分布"},
	{value:"139",label:"四星冒险者等级分布"},
	{value:"140",label:"五星冒险者等级分布"},
	{value:"141",label:"冒险者种族职业分布"},
	{value:"142",label:"冒险者来源"},
	{value:"143",label:"关卡完成情况分布(去重)"},
	{value:"144",label:"Phase分布"},
	{value:"145",label:"Task分布(去重)"},
	{value:"146",label:"Tutorial近期趋势"},
	{value:"147",label:"Tutorial进行中分布"},
	{value:"148",label:"冒险者招募类型对比分布"},
	{value:"149",label:"冒险者兑换分布"},
	{value:"150",label:"宝石总收支"},
	{value:"151",label:"一星英雄等级分布"},
	{value:"152",label:"二星英雄等级分布"},
	{value:"153",label:"三星英雄等级分布"},
	{value:"154",label:"四星英雄等级分布"},
	{value:"155",label:"五星英雄等级分布"},
	{value:"156",label:"英雄星级分布"},
	{value:"157",label:"关卡扫荡分布"},
	{value:"158",label:"关卡扫荡分布(去重)"},
	{value:"159",label:"PvPCount"},
	{value:"160",label:"PvPAvg"},
	{value:"161",label:"PvP冒险者分布"},
	{value:"162",label:"PvP技能分布"},
	{value:"163",label:"PvP冒险者胜率分布"},
	{value:"164",label:"PvP技能胜率分布"},
	{value:"165",label:"奥德赛统计"},
	{value:"166",label:"国家map"},
	{value:"167",label:"最后关卡"},
	{value:"168",label:"过场动画分析"},
	{value:"169",label:"获取宝石总数"},
	{value:"170",label:"消耗宝石总数"},
	{value:"171",label:"宝石获取分布"},
	{value:"172",label:"金币获取总数"},
	{value:"173",label:"金币消耗总数"},
	{value:"174",label:"金币获取分布"},
	{value:"175",label:"金币消耗分布"},
	{value:"176",label:"获取扫荡券总数"},
	{value:"177",label:"消耗扫荡券总数"},
	{value:"178",label:"扫荡券获取分布"},
	{value:"179",label:"扫荡券消耗分布"},
	{value:"180",label:"获取宝石总数-付费用户"},//付费用户
	{value:"181",label:"真宝石获取总数-付费用户"},
	{value:"182",label:"消耗宝石总数-付费用户"},
	{value:"183",label:"宝石获取分布-付费用户"},
	{value:"184",label:"宝石消耗分布-付费用户"},
	{value:"185",label:"金币获取总数-付费用户"},
	{value:"186",label:"金币消耗总数-付费用户"},
	{value:"187",label:"金币获取分布-付费用户"},
	{value:"188",label:"金币消耗分布-付费用户"},
	{value:"189",label:"单位时间玩家数量"},
	{value:"190",label:"国别(活跃度)"},
	{value:"191",label:"玩家等级和pvp关系对应分布（总量）"},
	{value:"192",label:"玩家人数与pvp关系对应分布"},
	{value:"193",label:"玩家等级和pvp关系对应分布（平均量）"},
	{value:"194",label:"国别(用户)"},
	{value:"195",label:"酒馆等级"},
	{value:"999",label:"nodejs占用内存-压力测试"},
	{value:"998",label:"mongodb占用内存-压力测试"},
	{value:"997",label:"mongodb活跃线程数量-压力测试"},
	{value:"899",label:"cron命令"},
	// {value:'1010',label:"周留存"},
	// {value:'10010',label:"月留存"},
	{value:'15001',label:"LogOn"},
	{value:'15002',label:"LogOut"},
	{value:'15003',label:"Register"},
	{value:'15004',label:"PvP"},
	{value:'15005',label:"BePvP"},
	{value:'15006',label:"PvPFinish"},
	{value:'15007',label:"BePvPFinish"},
	{value:'15008',label:"AdvOut"},
	{value:'15009',label:"AdvIn"},
	{value:'15010',label:"AdvEat"},
	{value:'15011',label:"AdvGene"},
	{value:'15012',label:"AdvLearnSkill"},
	{value:'15013',label:"AdvSummon"},
	{value:'15014',label:"AdvUpWeapon"},
	{value:'15015',label:"AdvUpArmor"},
	{value:'15016',label:"AdvUpItem"},
	{value:'15017',label:"AdvUpSkill"},
	{value:'15018',label:"AdvSetPvP"},
	{value:'15019',label:"AdvUpStar"},
	{value:'15020',label:"AdvLvUp"},
	{value:'15021',label:"FamiliarEat"},
	{value:'15022',label:"FamiliarUpSkill"},
	{value:'15023',label:"ChapterUnlock"},
	{value:'15024',label:"DishCook"},
	{value:'15025',label:"DishCookFinish"},
	{value:'15026',label:"DishCookCancel"},
	{value:'15027',label:"QuestStart"},
	{value:'15028',label:"QuestFinish"},
	{value:'15029',label:"QuestAbandon"},
	{value:'15030',label:"QuestSpin"},
	{value:'15031',label:"QuestResetCount"},
	{value:'15032',label:"QuestEliteStart"},
	{value:'15033',label:"QuestEliteFinish"},
	{value:'15034',label:"QuestEliteReset"},
	{value:'15035',label:"QuestRewardStart"},
	{value:'15036',label:"QuestRewardFinish"},
	{value:'15037',label:"QuestEliteSwitch"},
	{value:'15038',label:"QuestUnlock"},
	{value:'15039',label:"RoomUnlockSkill"},
	{value:'15040',label:"RoomLvUp"},
	{value:'15041',label:"RoomAdd"},
	{value:'15042',label:"SmithMakeStart"},
	{value:'15043',label:"SmithMakeFinish"},
	{value:'15044',label:"SmithMakeCancel"},
	{value:'15045',label:"SmithStrongStart"},
	{value:'15046',label:"SmithStrongFinish"},
	{value:'15047',label:"SmithDecompose"},
	{value:'15048',label:"SmithStrongCancel"},
	{value:'15049',label:"StorageSell"},
	{value:'15050',label:"StorageDiffDay"},
	{value:'15051',label:"StorageAdd"},
	{value:'15052',label:"StorageRemove"},
	{value:'15053',label:"StorageTakeOut"},
	{value:'15054',label:"TaskUp"},
	{value:'15055',label:"TavernUpEnergy"},
	{value:'15056',label:"TavernBuyGem"},
	{value:'15057',label:"TavernLvUp"},
	{value:'15058',label:"ItemAdd"},
	{value:'15059',label:"ItemRemove"},
	{value:'15060',label:"ShopRefresh"},
	{value:"15061",label:"ShopPurchase"},
	{value:"15062",label:"MailNew"},
	{value:"15063",label:"MailRemove"},
	{value:"15064",label:"MailTake"},
	{value:"15065",label:"NormalShopRefresh"},
	{value:"15066",label:"OdysseyShopRefresh"},
	{value:"15067",label:"PvPShopRefresh"},
	{value:"15068",label:"CoinShopRefresh"},
	{value:"15069",label:"GemShopPurchase"},
	{value:"15070",label:"CoinShopPurchase"},
	{value:"15071",label:"PvPCoinShopPurchase"},
	{value:"15072",label:"OdysseyCoinShopPurchase"},
	{value:"15073",label:"FameShopPurchase"},
	{value:"15074",label:"QuestSweep"},
	{value:"15075",label:"BuyGemBuy"},
	{value:"15076",label:"BuyGemOther"},
	{value:"15077",label:"SubGemBuy"},
	{value:"15078",label:"SubGemOther"},
	{value:"15079",label:"Revenge"},
	{value:"15080",label:"BeRevenge"},
	{value:"15081",label:"AdvUpEquipSet"}
	//商店刷新 和商店支付，mail新建，发送，删除，扫荡
//######end
	] },
	count:{type:Number,default:0,required:true,index:true},
	countObj:{type:String,default:""},//存储柱状图数据，最好改成obj类型存储
	country:{type:String},//国别
	onlypaid:{type:Boolean},
	region:{type:Number}
});

Statistical.schema.virtual('content.full').get(function() {
	return this.content.extended || this.content.brief;
});

Statistical.defaultColumns = 'logDate';
Statistical.register();

// exports = module.exports = function(){
// 	return new StatisticalManager;
// }
// var StatisticalManager = function(){

// }

// StatisticalManager.prototype.Analyze = function(){

// }
